### ISSUE TITLE
MotionSensor item not changing

### ISSUE THREAD

**Issue by silverman10** [BobRak/OpenHAB-Smartthings#10]
Hi,
I added a motion sensor thing and item. I can see that the channel state changing, but the item state doesnt change and trigger a rule.
Where am I going wrong?

openhab logs
```
21:05:50.499 [DEBUG] [rtthings.internal.SmartthingsServlet] - Smartthings servlet service() called with: 192.168.0.113: POST /smartthings/state
21:05:50.501 [DEBUG] [rtthings.internal.SmartthingsServlet] - Smartthing servlet function requested: state with Method: POST
21:05:50.507 [DEBUG] [rtthings.internal.SmartthingsServlet] - Smartthing servlet processing "state" request. data: {"deviceDisplayName":"Sensor1","value":"active","capabilityAttribute":"motion"}
21:05:50.509 [DEBUG] [s.internal.SmartthingsHandlerFactory] - Event received on topic: org/openhab/binding/smartthings/state
21:05:50.520 [INFO ] [ings.handler.SmartthingsThingHandler] - Smartthings updated State for channel: smartthings:motionSensor:Home:MSense:motion to active

```
Items
`Contact  Sensor  { channel="smartthings:motionSensor:Home:MSense:motion" }`

**Comment by BobRak** [comment]
I've been away for a few days and am trying to get caught up. Also, I need to refresh myself on OpenHAB configuration. I'll try to investigate in the next couple of days and get back to you. In the mean time it would be helpful if you sent me the thing definition and the relevant part of the rules file.

Does your thing look like this:
motionSensor MSense [ smartthingsName="Sensor1" ]

Bob

**Comment by silverman10** [comment]
Hi,
thanks. Thing definition as below
`
      Thing motionSensor             MSense           [ smartthingsName="Sensor1" ]
`

**Comment by silverman10** [comment]
more info. noticed this when i restarted the openhab service.
```

17:46:45.417 [INFO ] [smarthome.event.ThingAddedEvent     ] - Thing 'smartthings:motionSensor:Home:MSense' has been added.
17:46:45.417 [DEBUG] [s.internal.SmartthingsHandlerFactory] - SmartthingsHandlerFactory is now processing ThingTypeUID smartthings:motionSensor
17:46:45.418 [DEBUG] [s.internal.SmartthingsHandlerFactory] - Creating thing handler for smartthings:motionSensor
17:46:45.430 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'smartthings:motionSensor:Home:MSense' changed from UNINITIALIZED to INITIALIZING
17:46:45.431 [INFO ] [ings.handler.SmartthingsThingHandler] - No converter exists for motion (org.openhab.binding.smartthings.internal.converter.SmartthingsMotionConverter)
17:46:45.436 [INFO ] [ings.handler.SmartthingsThingHandler] - Using converter default
17:46:48.451 [INFO ] [ings.handler.SmartthingsThingHandler] - Attempt to send command to the Smartthings hub failed with: 
java.util.concurrent.ExecutionException: java.net.NoRouteToHostException: No route to host
	at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118)[69:org.eclipse.jetty.client:9.2.19.v20160908]
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:110)[69:org.eclipse.jetty.client:9.2.19.v20160908]
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:655)[69:org.eclipse.jetty.client:9.2.19.v20160908]
	at org.openhab.binding.smartthings.internal.SmartthingsHttpClient.sendDeviceCommand(SmartthingsHttpClient.java:58)[216:org.openhab.binding.smartthings:2.2.0.201708312359]
	at org.openhab.binding.smartthings.handler.SmartthingsThingHandler.handleCommand(SmartthingsThingHandler.java:112)[216:org.openhab.binding.smartthings:2.2.0.201708312359]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:207)[106:org.eclipse.smarthome.core.thing:0.9.0.b5]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.informHandlerAboutLinkedChannel(ThingLinkManager.java:264)[106:org.eclipse.smarthome.core.thing:0.9.0.b5]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:304)[106:org.eclipse.smarthome.core.thing:0.9.0.b5]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:1)[106:org.eclipse.smarthome.core.thing:0.9.0.b5]
	at org.eclipse.smarthome.core.events.AbstractTypedEventSubscriber.receive(AbstractTypedEventSubscriber.java:50)[99:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:192)[99:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1)[99:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:181)[99:org.eclipse.smarthome.core:0.9.0.b5]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748)[:1.8.0_144]
Caused by: java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)[:1.8.0_144]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)[:1.8.0_144]
	at org.eclipse.jetty.io.SelectorManager.finishConnect(SelectorManager.java:341)[72:org.eclipse.jetty.io:9.2.19.v20160908]
	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.processConnect(SelectorManager.java:676)[72:org.eclipse.jetty.io:9.2.19.v20160908]
	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.processKey(SelectorManager.java:645)[72:org.eclipse.jetty.io:9.2.19.v20160908]
	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:612)[72:org.eclipse.jetty.io:9.2.19.v20160908]
	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.run(SelectorManager.java:550)[72:org.eclipse.jetty.io:9.2.19.v20160908]
	at org.eclipse.jetty.util.thread.NonBlockingThread.run(NonBlockingThread.java:52)[84:org.eclipse.jetty.util:9.2.19.v20160908]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)[84:org.eclipse.jetty.util:9.2.19.v20160908]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)[84:org.eclipse.jetty.util:9.2.19.v20160908]
	... 1 more
17:46:48.466 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'smartthings:motionSensor:Home:MSense' changed from INITIALIZING to ONLINE
```
I wonder why it said it  couldnt connect to the hub? when i activated the sensor, i then did see it passed onto the openhab server.
```
17:49:53.593 [DEBUG] [rtthings.internal.SmartthingsServlet] - Smartthings servlet service() called with: 192.168.0.113: POST /smartthings/state
17:49:53.599 [DEBUG] [rtthings.internal.SmartthingsServlet] - Smartthing servlet function requested: state with Method: POST
17:49:53.605 [DEBUG] [rtthings.internal.SmartthingsServlet] - Smartthing servlet processing "state" request. data: {"deviceDisplayName":"Sensor1","value":"inactive","capabilityAttribute":"motion"}
17:49:53.609 [DEBUG] [s.internal.SmartthingsHandlerFactory] - Event received on topic: org/openhab/binding/smartthings/state
17:49:53.620 [INFO ] [ings.handler.SmartthingsThingHandler] - Smartthings updated State for channel: smartthings:motionSensor:Home:MSense:motion to inactive
17:50:14.450 [DEBUG] [rtthings.internal.SmartthingsServlet] - Smartthings servlet service() called with: 192.168.0.113: POST /smartthings/state
17:50:14.456 [DEBUG] [rtthings.internal.SmartthingsServlet] - Smartthing servlet function requested: state with Method: POST
17:50:14.465 [DEBUG] [rtthings.internal.SmartthingsServlet] - Smartthing servlet processing "state" request. data: {"deviceDisplayName":"Sensor1","value":"active","capabilityAttribute":"motion"}
17:50:14.471 [DEBUG] [s.internal.SmartthingsHandlerFactory] - Event received on topic: org/openhab/binding/smartthings/state
17:50:14.482 [INFO ] [ings.handler.SmartthingsThingHandler] - Smartthings updated State for channel: smartthings:motionSensor:Home:MSense:motion to active

```
Hope this helps in investigation

**Comment by BobRak** [comment]
The message "No converter exists for motion ..." is deceiving. It means there is no custom converter implemented for motion. On the next line you see "Using converter default" which means the default converter is being used. This is OK.

From the java.net.NoRouteToHostException it seems like the hub was offline or disconnected for a bit. But after that I see messages being sent to the hub and responses. So, I think it is working OK.

In your original message you said "I can see that the channel state changing, but the item state doesnt change and trigger a rule." What do you mean channel state and item state? Do you have the motion displayed in a sitemap and is that working? What is the rule that isn't working? At this point I'm not clear about what is not working.

**Comment by silverman10** [comment]
I was expecting a message on the log that said 
item Sensor changed from Inactive to active
Or from close to open.

This hasnt happened. All i see is "Smartthings updated State for channel: smartthings:motionSensor:Home:MSense:motion to active" . This means that openhab is getting the events from SmartThings hub, its just that the item state doesnt change according to that.

The rule i have is simple
"
rule "Handle PIR Events"
when
    Item Sensor received update
then
    Bedroomspeaker.sendCommand(ON)
end
"

Hope it is clear now

**Comment by BobRak** [comment]
## Sitemap
First of all, do you show the state of the motion sensor on your sitemap? If not please add it first and see what happens there.

## Logs
I don't know what platform you are running openHAB on. I am using a Raspberry Pi. There there are 2 log files in /var/log/openhab2: openhab.log - On that one I see messages like you sent me. There is also events.log that has messages like:
`2017-11-22 08:51:34.694 [ItemStateChangedEvent     ] - MasterBedroomLight changed from ON to OFF
2017-11-22 08:51:36.102 [ItemStateChangedEvent     ] - MasterBedroomLight changed from OFF to ON
`
Do you have an events.log file. If so, what do you see there?

## Rules file
I'm not an expert at the rules but I do have a rules file. Here is part of mine:

`rule "HomeAway"
    when   
        Item HomeAway received command
    then   
        logDebug("Rules", "HomeAway received a command")
        if( HomeAway.state == ON ) {
            homeAway = "away"
            // Things that should never be on when away are set to off here
            sendCommand(BobSwitchF1, OFF)
            sendCommand(BobDimmerF2, OFF)
            sendCommand(BobSwitchF5, OFF)
        }
        else {
            homeAway = "home"
        }
        postUpdate(CurrentHomeAway, homeAway)
        logInfo( "Rules", "homeAway set to {}", homeAway)
    end

`

Note I used received command instead of received update, I also am using the logInfo() command so I can see in my rules.log file what is actually happening in the rules. Are you sure your rules are working as expected? Here is a sample from my rules.log file
`2017-11-22 07:00:00.036 [Rules                     ] - Pump turned on
2017-11-22 07:30:00.048 [Rules                     ] - Kitchen plug turned on
2017-11-22 08:00:00.036 [Rules                     ] - Office plug turned off
2017-11-22 09:00:00.036 [Rules                     ] - Kitchen plug turned off
`

**Comment by silverman10** [comment]
# **Sitemap**
`		Text item=Sensor label="Sensor State"`
it just shows empty on the sitemap.

# **Logs**
I too am on an ubuntu server, version 14.04. The logs i shared were from the karaf consol; output from log:tail. I checked the events.log file too, but there isnt anythere there.

# **Rules**
I have tried the received command too, but the rule doesnt trigger. 

I am not too familiar with items and Things, but could the issue be that I am using a Contact item for motionSensor "Thing". as I read, "Contact" item uses "closed" and "opened" statuses, but the motion sensor gets an "active" and "inactive". could this be causing an incompatibility?

**Comment by BobRak** [comment]
I'll have to run the code in the Java debugger to understand exactly what is happening. I'm going to be unavailable the rest of this week. I'll have a look next week when I get back.

**Comment by silverman10** [comment]
thanks. 
I should tell you that I have tried this with a Xiaomi Aqara button as well, and can see the same behavior.
I see the below, but cant see the item state changing. Item is still NULL

```
20:47:53.865 [DEBUG] [rtthings.internal.SmartthingsServlet] - Smartthings servlet service() called with: 192.168.0.113: POST /smartthings/state
20:47:53.870 [DEBUG] [rtthings.internal.SmartthingsServlet] - Smartthing servlet function requested: state with Method: POST
20:47:53.876 [DEBUG] [rtthings.internal.SmartthingsServlet] - Smartthing servlet processing "state" request. data: {"deviceDisplayName":"Button1","value":"pushed","capabilityAttribute":"button"}
20:47:53.881 [DEBUG] [s.internal.SmartthingsHandlerFactory] - Event received on topic: org/openhab/binding/smartthings/state
20:47:53.885 [INFO ] [ings.handler.SmartthingsThingHandler] - Smartthings updated State for channel: smartthings:button:Home:ButtonThing:button to pushed

openhab> smarthome:items list
BButton (Type=SwitchItem, State=NULL, Label=null, Category=null)

```

```
Thing button ButtonThing           [ smartthingsName="Button1" ]
Switch  BButton   { channel="smartthings:button:Home:ButtonThing:button" }

```
```
 96c7a3bc-c025-450a-b5b9-8e7b4e755230 20:51:35: debug Forwarding device event to openhabDevice: {"path":"/smartthings/state","body":{"deviceDisplayName":"Button1","value":"pushed","capabilityAttribute":"button"}} 

```

**Comment by BobRak** [comment]
I think I have an answer for the motionSensor. First of all, there is a bug in the smartthing SmartApp. Logon to the Smartthings developers website and select "My SmartApps" > bobrak:OpenHabAppV2. At line 219 you should find the following block
`    "motionSensors": [
        name: "Motion Sensor",
        capability: "capability.motionSensor",
        attributes: [
            "motion"
        ],
        action: "actionActiveInactive"
`
Change motionSensors to motionSensor.  Save the change and then Publish > For me

#### Secondly
I did not set this up as a Contact. You can use an item definition like:
`String Sensor"Mike Maxwells simulator [%s]"    { channel="smartthings:motionSensor:Home:MSense:motion" }
`

The sitemap should look like one of the following:
`Text item=Sensor`
`Switch  item=Sensor mappings=[active="Active", inactive="Inactive"]`

#### Third
I'll look into the button issue when I have a chance.

**Comment by silverman10** [comment]
thank you. I have updated the SmartApp.

**Comment by silverman10** [comment]
I have also noticed that i get the below warning occasionally. It goes away after a couple of restarts. Is this again because the hub is not reachable?
```

18:40:27.708 [DEBUG] [rtthings.internal.SmartthingsServlet] - Smartthings servlet service() called with: 192.168.0.113: POST /smartthings/state
18:40:27.710 [DEBUG] [rtthings.internal.SmartthingsServlet] - Smartthing servlet function requested: state with Method: POST
18:40:27.717 [DEBUG] [rtthings.internal.SmartthingsServlet] - Smartthing servlet processing "state" request. data: {"deviceDisplayName":"Sensor1","value":"inactive","capabilityAttribute":"motion"}
18:40:27.719 [DEBUG] [s.internal.SmartthingsHandlerFactory] - Event received on topic: org/openhab/binding/smartthings/state
18:40:27.722 [WARN ] [s.internal.SmartthingsHandlerFactory] - Unable to locate handler for display name: Sensor1 with attribute: motion
18:41:08.500 [DEBUG] [rtthings.internal.SmartthingsServlet] - Smartthings servlet service() called with: 192.168.0.113: POST /smartthings/state
18:41:08.503 [DEBUG] [rtthings.internal.SmartthingsServlet] - Smartthing servlet function requested: state with Method: POST
18:41:08.509 [DEBUG] [rtthings.internal.SmartthingsServlet] - Smartthing servlet processing "state" request. data: {"deviceDisplayName":"Sensor1","value":"active","capabilityAttribute":"motion"}
18:41:08.515 [DEBUG] [s.internal.SmartthingsHandlerFactory] - Event received on topic: org/openhab/binding/smartthings/state
18:41:08.518 [WARN ] [s.internal.SmartthingsHandlerFactory] - Unable to locate handler for display name: Sensor1 with attribute: motion

```

**Comment by BobRak** [comment]
Are you talking about the message: 
> Unable to locate handler for display name: Sensor1 with attribute: motion

Off hand this looks like a configuration issue. Please send me the line out of your things, items and sitemap files for things related to Sensor1.

Thanks,

**Comment by BobRak** [comment]
I created a button simulator so I could test the button functionality and it does work for me. Here are my definitions:
Thing:
`button                   MikesButtons            [ smartthingsName="Mike Maxwells simulator" ]`

Item:
`String MikesButtonSimulator   "Mike Maxwells button simulator [%s]"                                { channel="smartthings:button:Home:MikesButtons:button"  }`

Sitemap:
`Text item=MikesButtonSimulator
Switch  item=MikesButtonSimulator   mappings=[pushed="Pushed", held="Held"]`

The item will have to be setup as a String since this is what the binding returns. If this doesn't solve your issue please send me your thing, item and sitemap lines

Thanks,

Bob

**Comment by silverman10** [comment]
Yes, that works now. String item works. I was using a Switch item. Great, thank you.
For the error "Unable to locate handler for display name: Sensor1 with attribute: motion", its the same things,item and sitemap as given earlier. Dont really think its a config issue, as I said, a restart or reboot fixes it and its intermittent.
