### ISSUE TITLE
ST Multisensor not displaying values

### ISSUE THREAD

**Issue by kulasangeles** [BobRak/OpenHAB-Smartthings#100]
Hi @BobRak first of all, thank you for creating this excellent binding.

I have an issue wherein I literally copied your set-up here (modifying values of course to my set-up) but I am still getting Null states for my two multi sensors. (contact sensor, temperature, battery). 

I checked openhab and smarthings logs and they seem to be communicating. Note that the switches for me are working. 

Am I missing any set-up?

**Comment by BobRak** [comment]
In the very last step of the [Smartthings Installation](https://www.openhab.org/addons/bindings/smartthings/doc/SmartthingsInstallation.html) document you have to add all of the devices you want to report back. Have you selected the Battery, Contact sensor and Temperature measurement items? Without this step smartthings can not send those values to the openHAB binding. This is the thing most people miss.

**Comment by kulasangeles** [comment]
Hey @BobRak it turned out the openhabdevice has incorrect IP and mac address.

So now temp, contact and battery are now showing for my garage multisensor. 

I tried to add the second one but it's not showing. I am sure I have the correct mapping.

**Comment by BobRak** [comment]
The only thing that I can think of is that you haven't added the second one in the smartapp as I described above.
