### ISSUE TITLE
Enh Request:  Add support for Lock()

### ISSUE THREAD

**Issue by kociubin** [BobRak/OpenHAB-Smartthings#11]
Could you please add support for smart locks?  I use a yale z-wave lock and it's not working because the necessary actions are not supported.  Please add support for the following attributes and commands for capability.lock

lock: ENUM

        The state of the lock device

        locked
            The device is locked
        unknown
            The state of the device is unknown
        unlocked
            The device is unlocked
        unlocked with timeout
            The device is unlocked with a timeout

Commands

    lock()
        Lock the device
    unlock()
        Unlock the device

**Comment by BobRak** [comment]
I looked at the lock definition in the binding and see it is setup as read only. You should be able to see the current value but probably not change it from openhab. Please send me you thing, item and sitemap definitions for the lock. Also please send me logs from openhab from when you change it from your smart phone.

What do you think "unlocked with timeout" is supposed to do?

Please see the Troubleshooting.md file to see how to look at logs and what to send me to help troubleshoot.

As time permits I will create a Lock simulator so I can test this device. I'll get back to you when I know more.

Thanks,

Bob

**Comment by kociubin** [comment]
I do have it working correctly as read-only.  Whenever I lock or unlock the door openhab correctly updates the status to "locked" or "unlocked".  

My lock is configured to automatically lock itself after 1 minute.  This is what they mean by "unlocked with timeout."  

Below are the relevant portions of the current setup and logs
 

```
//////////////////////////////////////
//Relevant Thing Definition    //
//////////////////////////////////////
Bridge smartthings:smartthings:Home    [ smartthingsIp="192.168.1.93", smartthingsPort=39500 ] {
	Thing lock  		  		STYaleLock     [ smartthingsName="Yale Lock" ]
}

//////////////////////////////////////
//Relevant Item Definition     //
//////////////////////////////////////
String  	STYaleLock       "Yale Lock"     { channel="smartthings:lock:Home:STYaleLock:lock" } 

//////////////////////////////////////
//Relevant Sitemap Definition  //
//////////////////////////////////////
Text item=STYaleLock

//////////////////////////////////////
//Relevant Log                      //
//////////////////////////////////////

2017-11-28 13:27:46.289 [INFO ] [ings.handler.SmartthingsThingHandler] - Smartthings updated State for channel: smartthings:lock:Home:STYaleLock:lock to unlocked
2017-11-28 13:27:54.387 [INFO ] [ings.handler.SmartthingsThingHandler] - Smartthings updated State for channel: smartthings:lock:Home:STYaleLock:lock to unlocked with timeout
2017-11-28 13:28:20.227 [INFO ] [ings.handler.SmartthingsThingHandler] - Smartthings updated State for channel: smartthings:lock:Home:STYaleLock:lock to locked
```

**Comment by BobRak** [comment]
Sorry I haven't had time to investigate this further. Right at the moment I have a lot going on in my life. The time consuming part is creating a simulator so I can test. If you have a chance can you try the following in your sitemap and let me know what happens:
Switch  item=STYaleLock mapping=[locked="Locked",unlocked="Unlocked"]

and in your item change "Yale Lock" to "Yale Lock [%s]"

Thanks.

**Comment by kociubin** [comment]
Your suggestion worked.  Thanks so much.  Everything works as expected.

 

BTW,  I corrected the misspelling in the sitemap line.  Instead of:

 

Switch item=STYaleLock mapping=[locked="Locked",unlocked="Unlocked"]

    I changed to: 

Switch item=STYaleLock mappings=[locked="Locked",unlocked="Unlocked"]

**Comment by BobRak** [comment]
Sorry about the spelling mistake on my response. I knew it was to late to look at the computer but I wanted to answer you as quickly as possible. 

Were you able to figure out a mapping for the "unlocked with timeout" attribute. If so, I'd appreciate seeing what you did.

**Comment by kociubin** [comment]
Thanks again for your help.  Your plugin is indispensable. 

 

I don’t need a mapping for “unlocked with timeout”.  It’s a temporary state that I don’t need to set.   The lock only stays in this state for 30 seconds and then locks itself.

**Comment by jluzonpr** [comment]
Got this two work over a year later. Thanks bud!
