### ISSUE TITLE
Error when attempting to install 3.2.0 on OH3

### ISSUE THREAD

**Issue by Mr-jreeves** [BobRak/OpenHAB-Smartthings#110]
openhabian running openHAB 3.2.0 Build #2469 on a Pi4 4GB with a 32GB SD Card

I attempted to install the Samsung ST 3.2.0.SNAPSHOT and it attempted both the 3.2.0Snapshot and the 3.2.0.M2 … (not sure if that’s normal) … anyway, after a minute or so, it fails with:

Error downloading mvn:com.thoughtworks.xstream/xstream/1.4.18

Tried a second time with the other one, same thing, both attempt to install, and then same error.

Any ideas?

**Comment by BobRak** [comment]
James:

I am no longer maintaining the version in my BobRak repo. The version in
the openHAB repo is maintained by the openHAB team. I do not have any ideas
about what is wrong. I suggest you post something on the openHAB community
website.

Bob

**Comment by Mr-jreeves** [comment]
Thanks Bob - Got it.
