### ISSUE TITLE
Unable to start in OpenHAB 2.2

### ISSUE THREAD

**Issue by Mustavio** [BobRak/OpenHAB-Smartthings#15]
Running on Windows. Fresh install of OpenHAB 2.2. This binding does not show up in PaperUI and when I try to start it I get this error:

204 | Installed |  80 | 2.2.0.201712120439     | Smartthings Binding

openhab> bundle:start 204
Error executing command: Error executing command on bundles:
        Error starting bundle 204: Could not resolve module: org.openhab.binding.smartthings [204]
  Unresolved requirement: Import-Package: org.apache.commons.codec

openhab>

**Comment by Mustavio** [comment]
I downloaded the apache commons codec jar from here:
https://commons.apache.org/proper/commons-codec/download_codec.cgi
and added it to my OpenHAB\Addons folder. After restarting, the Smartthings plugin starts correctly. Wondering why I did not have this addon by default?

**Comment by BobRak** [comment]
@Mustavio I'm not sure why you had this problem. I looked at my Windows installation which is a couple of months old now and the platform included commons.codec-1.9. And, my Raspberry Pi installation included commons.codex-1.6 I have not had to add this jar to my addons folder.
