### ISSUE TITLE
tamperAlert capability does not have a channel associated with it

### ISSUE THREAD

**Issue by anthonygillet** [BobRak/OpenHAB-Smartthings#20]
When using devices that have a tamperAlert capability there is no way to map an item to this Thing since there is no channel associated with it.  The log produces this output:

2017-12-27 18:01:11.759 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'tamper' for thing type 'smartthings:tamperAlert:Home:BackDoorSensor', because channel type 'smartthings:tamper-channel' could not be found.
2017-12-27 18:01:21.872 [WARN ] [ore.internal.thing.ThingTypeResource] - Cannot find channel type: smartthings:tamper-channel

**Comment by BobRak** [comment]
Anthony:

Yes, I can see that I have not defined a tamper-channel. I'll do that and deploy an updated module. You'll have to give me a few days as I am swamped with other things at the moment. Thanks for calling this to my attention. I have a limited number of devices I can test with.

**Comment by BobRak** [comment]
@anthonygillet 

I updated the code and want to let it run on my system for a few days. I should be able to push a new release to github in a few days.

Bob

**Comment by anthonygillet** [comment]
Thanks, looking forward to giving it a test!

**Comment by BobRak** [comment]
Anthony:

I just deployed a new release (including jar file) that corrects a number of issues with device configuration. This includes corrections to the tamperAlert thing type.

It also corrects a bug in the messages handling between OpenHAB and the Smartthings hub that cause slow response. This release is much faster. Thanks to @fx for figuring this out.

Please let me know if this fixes the tamperAlert or if something is still wrong.

Thanks,

Bob

**Comment by anthonygillet** [comment]
Tamper Alert is working now too with the new release.  Thanks again!
