### ISSUE TITLE
Can't Find in Discovery

### ISSUE THREAD

**Issue by AJax2012** [BobRak/OpenHAB-Smartthings#21]
Hey, I like the way this looks, but I'm having an issue with finding the device in Paper UI's discovery...Maybe you can help me figure out what I'm doing wrong? So far, I have:

1. Copied the Snapshot file to the addons folder
2. Created a .things, .items, .sitemaps file in config folders
3. Followed the steps provided in SmartThings API setup tutorial

I can't seem to even get a response after following these steps at all...Even in the logs. I created the OpenHAB log to try troubleshooting and I see information about an MQTT broker, starting the UIs and all the normal stuff...Nothing about SmartThings. I looked at some other issues from the past, and I tried to follow your advice from those, but I can't seem to find anything. The .things file references the SmartThings IP address and the normal port and the SmartThings device references the IP address and MAC of the OpenHAB hub. The only thing I can think of is that OpenHABian doesn't like the fact that I first installed the NPM version of [stjohnjohnson](https://github.com/stjohnjohnson/smartthings-mqtt-bridge) version of the SmartThings bridge. I can't figure out how to uninstall it though. Any thoughts? I feel like this should be working at this point, but I've been wrestling with this for days and have nothing to show for it.

**Comment by BobRak** [comment]
Hi:  To uninstall NPM I think you can do 
`npm uninstall -g smartthings-mqtt-bridge`
See {npm uninstall at:](https://docs.npmjs.com/cli/uninstall).

Please see issue #18. I think they are having the same issue.  I'll try a fresh install as soon as I get time and will let you know.

**Comment by AJax2012** [comment]
I think I missed the global flag...but I actually just tried to start from scratch and I think I might have ruined my MicroSD card :( I'll try again another day...

**Comment by BobRak** [comment]
OK, thanks for letting me know. I heard back from the other guy that was having a  similar problem (issue #18) and he had an error in his download. Once that was resolved he saw smartthings messages in the logs. When you try again make sure you get a good download and that the file permissions are correct.
