### ISSUE TITLE
Possible issue with humidity channel?

### ISSUE THREAD

**Issue by anthonygillet** [BobRak/OpenHAB-Smartthings#22]
I think the humidity sensor Thing ID may be defined incorrectly or inconsistently.  I am not able to get consistent updates from humidity sensors in my network.

In the official ST capabilities reference, humidity sensors are defined as relativeHumidityMeasurement.  They are also defined as relativeHumidityMeasurement in OpenHabAppV2.groovy and thing-types.xml

However, in SmartthingsBindingConstants.java, humidty sensors are defined with ID "humiditySensor".

I am totally guessing here, but perhaps this inconsistency is causing the performance issues with humidity sensors?

**Comment by BobRak** [comment]
I'll look into this.

There is a bug in the current version on github that affects performance. I was hoping to get a new release on github this past week. I'll look into what you are reporting and then will push the update to github.

**Comment by BobRak** [comment]
Anthony:

This should also be fixed now. Please let me know.

Thanks,

Bob

**Comment by anthonygillet** [comment]
The new jar is working for humidity updates.  I am getting values from each of my sensors now.  I'll try to test the new tamper alert channels tomorrow.  Thanks!
