### ISSUE TITLE
Smoke Detector carbonMonoxideDetector device discovered as "unknown"

### ISSUE THREAD

**Issue by megaoldgeek** [BobRak/OpenHAB-Smartthings#24]
Shows up in the inbox, but cant be added as a thing... see screen shot.
<img width="1435" alt="carbonmono" src="https://user-images.githubusercontent.com/35188323/34648357-72ded586-f366-11e7-986d-2fe7f5914c95.PNG">

When you click add a thing, Paper UI shows pops up a snackbar message - 409 - conflict.

018-01-07 04:52:06.989 [WARN ] [g.discovery.internal.PersistentInbox] - Cannot create thing. No binding found that supports creating a thing of type smartthings:carbonMonoxideDetector.

**Comment by BobRak** [comment]
I'm pretty sure that is fixed in my code that I am currently testing. I hope to be able to push that up to github in the next few days. There will also be some new instructions about using discovery. In summary make sure to add the "Smartthings hub" first.

**Comment by megaoldgeek** [comment]
Sweet I look forward to testing it!
Yeah I fumbled a bit with getting discovery to show up as an option on PaperUI... 
I then thoroughly re-read your instructions and found where I needed to add my hub IP and port.

**Comment by megaoldgeek** [comment]
Will the fix you have fix these too?

![image](https://user-images.githubusercontent.com/35188323/34655304-4a4797b0-f3d5-11e7-90bf-930b1b5fe046.png)

**Comment by BobRak** [comment]
I just deployed a new release (including jar file) that corrects a number of issues with device configuration. It also corrects a bug in the messages handling between OpenHAB and the Smartthings hub that cause slow response. This release is much faster. Thanks to @fx for figuring this out.

Hopefully this will fix all of your problems but that is probably being overly optimistic given how many devices you have that I don't and therefore haven't been able to test with. As long as people report issues I will work at fixing them.

Bob

**Comment by megaoldgeek** [comment]
Thanks Bob.  Loaded the new snapshot, same thing.
Good news the humidity sensors work and so do the tampers!

2018-01-09 00:52:40.932 [WARN ] [g.discovery.internal.PersistentInbox] - Cannot create thing. No binding found that supports creating a thing of type smartthings:carbonMonoxideDetector.

**Comment by megaoldgeek** [comment]
Some additional info...  Looks like it did find the mapping somewhat..

![image](https://user-images.githubusercontent.com/35188323/34707889-0c37b388-f4de-11e7-8be5-239d4bed7ed7.png)

**Comment by BobRak** [comment]
I have identified the problem. I'll implement a fix as soon as I can find time.

**Comment by megaoldgeek** [comment]
Awesome, thanks.

**Comment by BobRak** [comment]
Don:

I just pushed a new org.openhab.binding.smartthings-2.2.0-SNAPSHOT.jar file to github. It includes the CarbonMonoxideDetector correction. Please let me know if this solves that issue.

Also, I would appreciate it if you would let me know of anything else that doesn't work. Before too long I would like to submit this to OpenHAB for their review. Past experience (I did a cm11a (X-10) binding earlier) taught me that it may take as much as 6 months to go from my pull request to production.

Thanks,

Bob

**Comment by megaoldgeek** [comment]
Bob,

The new snapshot worked flawlessly for the CarbonMonoxideDetector.
I'll start another thread for other observations.

Thanks,
-don
