### ISSUE TITLE
 "Create the Device"... Documentation.

### ISSUE THREAD

**Issue by megaoldgeek** [BobRak/OpenHAB-Smartthings#25]
On the SmartHub documentation , item 9 under "Create the Device"...

Create the Device
  >>>      mac: (This is the same as the Device Network ID but with : between segments

I use the MAC without the colon and it works?  Any value to adding the : ?

**Comment by BobRak** [comment]
A mac address usually includes colons just to make it easier to view / enter. It is a convention. I would prefer not to change the documentation at this point as I would be obligated to test it. And, that would take time away from fixing bugs and deploying a new release.  I will keep in mind to later change the documentation to say the colons are optional.
