### ISSUE TITLE
Channel Tamper for motion

### ISSUE THREAD

**Issue by megaoldgeek** [BobRak/OpenHAB-Smartthings#26]
2018-01-07 18:00:47.409 [WARN ] [ore.internal.thing.ThingTypeResource] - Cannot find channel type: smartthings:tamper-channel

During discovery... all my 4 in 1 Zooz tamper channels are ignored.

**Comment by BobRak** [comment]
This will be fixed in the next release. See issue #20.

There are a number of device fixes which will be included in this release. Please no more issue until I am able to push a new release. This is just slowing me down.

Thanks

**Comment by megaoldgeek** [comment]
Works Great Thanks
