### ISSUE TITLE
Is there a limit to the number of devices?

### ISSUE THREAD

**Issue by scamiran149** [BobRak/OpenHAB-Smartthings#35]
Hello,

It seems as if I cannot use all of my devices, but only a certain number at a time. I haven't figured out exactly how many.

Is there a particular limit I should be aware of? Or is it possible one of my devices is bugging out discovery from OpenHAB?

Thank,

Sherwin

**Comment by scamiran149** [comment]
A quick follow up-- it appears there is some kind of soft-limit on discoverable devices, in that new devices are not automatically appearing in my OpenHAB2 configuration.

That being said, devices that are not being discovered as Things can still work, you just have to manually create the Things using the Smartthings Name, and appropriate category. If the name in Smartthings changes, the name in the OpenHAB2 thing has to change as well.

I'm actually using the binding backwards; my main goal is to tie virtual smarttthings "things" to OpenHAB2, and use those to control UPB devices from Smartthings. It seems to be working really well.

Thank you much! If there is additional troubleshooting I can do about device discovery or other interactions I would be happy to do so.

**Comment by BobRak** [comment]
I'm not aware of a limit on the number of discoverable devices. A couple of months ago another user reported that not all of his devices were being discovered. We discovered that Smartthings has a limit on the size of the data stream it can return. I made a change that broke the discovery result into separate messages of ~30k bytes. You should make sure you have this release which was pushed out a couple of months ago. If you have done your download in the last 2 months you should have the latest. to be sure look at your OpenHabAppV2.groovy with the one in the repo [HERE](https://github.com/BobRak/OpenHAB-Smartthings/blob/master/org.openhab.binding.smartthings/src/main/smartthings/SmartApps/OpenHabAppV2.groovy). At line 692 you will see a check on the bufferLength. If yours doesn't have that you should get the latest release.  You can read more about this in closed issue #27.

The Smartthings app: OpenHabAppV2 logs each device that it discovers and logs that to the Smartthings log. Please look in that log for things that are missing in your discovery result. Also, OpenHab logs each device it discovers so you can look there to confirm that each device that Smartthings sends is processed by OpenHAB.  By comparing the two logs maybe you can see where a particular device is failing to be discovered.

I wouldn't be surprised if there are cases that are not handled correctly by the binding. Especially in the discovery phase. 

I would be interested in knowing how many devices you have.

Please let me know what you find. I would be willing to add more logging to either the SmartApp or openHAB if that would help.

Bob

**Comment by scamiran149** [comment]
Sorry for the VERY LONG delay in my response.

I was still having the problem, but figured out the issue. some of my device names had brackets  " ( " " ) " in the names. See the following error:

java.lang.IllegalArgumentException: ID segment 'NestWeather(60016)' contains invalid characters. Each segment of the ID must match the pattern [A-Za-z0-9_-]*.
I also had problems with apostrophies, and I think Smartthings automatically uses them for presence devices on android.

I'm guessing I still got some devices to show up, because the discovery was broken up into messages of 30k bytes, and only the ones with an invalid device name failed.
