### ISSUE TITLE
Should this binding work with the new Samsung Connect Home (Smartthings) hub?

### ISSUE THREAD

**Issue by 5witch** [BobRak/OpenHAB-Smartthings#36]
I installed the Smartthings Binding but I'm not getting anything when I "Search for Things".  I don't see anything logged on the Smartthings "Live Logging".  Then I thought I should check if this binding will even work with the new Smartthings hardware.  It does appear to be using the same port (39500).

Samsung Connect Home
Firmware Version | 000.017.00055
-- | --
Hardware Version | Samsung Connect Home, US_CA

**Comment by 5witch** [comment]
I figured out my problem.  I missed this rather crucial step:
"Prior to running starting the binding the Smartthings hub must have the required OpenHAB software installed. Follow these instructions"

**Comment by BobRak** [comment]
Thanks for the update. I was guessing that you may have missed a step somewhere along the way. It is a rather long and complicated installation.

I also noticed that "live Logging" wasn't working for me either. I found [This](https://community.smartthings.com/t/no-live-logging-ever/92074) post. And, sure enough when I logged in using [https://account.smartthings.com](https://account.smartthings.com) I started seeing logs.

Bob
