### ISSUE TITLE
 [WARN ] [s.internal.SmartthingsHandlerFactory] - Unable to locate handler for display name: Lolas Room door with attribute: temperature

### ISSUE THREAD

**Issue by 5witch** [BobRak/OpenHAB-Smartthings#39]
I tried to setup temperature items for my Samsung multipurpose sensors. I remove them but Openhab seams to remember them somewhere. I see warnings like:   [WARN ] [s.internal.SmartthingsHandlerFactory] - Unable to locate handler for display name: Lolas Room door with attribute: temperature.

I'm not sure if this problem is specific to OpenHab2 or the Binding.  I can't find "Lola" in any of the items or other txt files.

**Comment by BobRak** [comment]
This is one part of OpenHAB I'm pretty fuzzy on. Is it possible that you originally set the device up using the paperUI? The things discovered through discovery vs. defined through files are separate.  Maybe this is stuff you already know... I would suggest checking the paperUI (configuration -> things) and the config files in the things directory. Removing one or the other if there are duplicates.

I also have 2 of these devices and do have them working fine with the binding.

Please let me know. And, accept my apology if I'm telling you things you already know.

Bob

**Comment by BobRak** [comment]
Have you been able to figure out where the device info is being stored and remove it?

**Comment by 5witch** [comment]
I've just been ignoring this.  But today, having a better understanding of the binding, I unchecked these items from the OpenHabAppV2 automation in the Smartthings app, and the message stopped.

**Comment by BobRak** [comment]
Is this thing defined in files or through the paperUI. If in files please send me the definition in the .items and .things files. If in paperUI please send me a screenshot of the definition. From what you've given me I have no idea what kind of a thing it is.

I am currently without my computer and it will be a couple of weeks until I can look into anything. But, then I should have more time to devote to openHAB.

Bob

**Comment by 5witch** [comment]
It's not in openhab at all.  These show up in  "temperature measurement" section of the OpenHabappV2 smart app Automatons options.

**Comment by BobRak** [comment]
Is this still an issue?

If it is showing up in "temperature measurement" section of the OpenHabappV2 smart app then it will report changes to openHab. It it isn't defined in openHab then openHab will log an error everytime the temperature changes and the hub sends a notification to openHab. You should either remove it from the OpenHabappV2 or define it on the openHab section.
