### ISSUE TITLE
Slow Feedback from SmartThings Sensors To OpenHAB

### ISSUE THREAD

**Issue by matdmiller** [BobRak/OpenHAB-Smartthings#4]
I am experiencing pretty slow feedback from the my smart things sensors back to openhab.  For example motion sensor states and power meter states are taking from 5 to 45 seconds to update in openhab.  Is there something I can do to improve this?

**Comment by BobRak** [comment]
I have the Smartthings outlet which includes a power meter. I've seen a delay as well with the power meter but I don't think it has been more than 10-15 sec. I think that is just how long the sensor is waiting to send an update to the hub. That is just my guess. But, it needs to wait a reasonable time to get a stable reading. 

If you want to try to isolate where the delay is coming then I would recommend opening the log window in the Smartthings developers console and tail the openHAB logs. Then when you change the switch on the outlet you can see how long it takes for the change to show up in smartthings and in openHAB.

Please let me know what you find.

**Comment by fx** [comment]
Hey @BobRak, here's some more info:

I'm seeing request delays of roughly ~10s for any `POST` to `/smartthings/state` from the smartthings device. From a quick glance, it looks to me as if there is some rate limiting in effect and it's using a single queue to work through any updates. As such, updates are incredibly delayed.

It's not that the device handler's `deviceNotification` is blocking, it's definitely the `hubAction` going into a queue being walked off one by one with about 10s delay in between jobs.

They do have a rate limit of 250 events per minute, saying any events past 250 would be dropped until 60 seconds are up. Doubt that's the cause though, I'm nowhere near that number.

I don't see any information alluding to limits in [HubAction](http://docs.smartthings.com/en/latest/ref-docs/hubaction-ref.html?highlight=HubAction) or [sendHubCommand](http://docs.smartthings.com/en/latest/ref-docs/smartapp-ref.html#sendhubcommand) and can't even tell at a glance how the returned `HubAction` gets sent.

Can you see why that is and if there's a workaround?
