### ISSUE TITLE
When trying to discover "Things" in step 9 through the SmartThings binding, nothing is discovered.

### ISSUE THREAD

**Issue by ShermanThruGA** [BobRak/OpenHAB-Smartthings#45]
Sorry, I may be doing something stupid, but I cannot discover any "Things" through the SmartThings binding. 

I've gotten everything connected and am in the Inbox under the SmartThings binding, and run discovery, but nothing is found.

Is there something else that must be enabled to have discovery work? 

I have also set up the SmartApp, Device Handler, and Device. I've exposed the relevant SmartThings devices through the Smart App in the SmartThings native app.

Thanks a lot!

**Comment by BobRak** [comment]
Did everything go as expected in steps 1 - 8? Have you looked at the openHAB logs? There should be information logged in there if it is able to successfully connect to the Smartthings Hub. What do you see there? Please send some of the log file around where openHAB and the hub are communicating.

You can also try to manually configure the hub and add some things manually just to confirm openHAB is talking to the hub.

**Comment by BobRak** [comment]
One more thing... Did you perform the steps in SmartthingsInstallation.md? In the last section, did you successfully complete step 7 in the **Configuration in the Smartthings App** section

**Comment by BobRak** [comment]
Are you now able to discover things? Please let me know how things have gone.
