### ISSUE TITLE
Trying to setup two openhab instances using same Smarthings Hub

### ISSUE THREAD

**Issue by 5witch** [BobRak/OpenHAB-Smartthings#46]
After getting my OpenHAB working with OpenHAB-Smartthings, I cloned my Raspberry Pi to a second device and changed the IP address & device name.  Then I duplicated the OpenHab-Smartthings setup making minor changes to the code pasted into the Smartthings developer site.  For example the second mySmartApp is called OpenHabAppV2_2 
with code change
definition(
    name: "OpenHabAppV2_2"...

and 

My Device Handler is bobrak : OpenHabDeviceHandler2 with code change
    definition (name: "OpenHabDeviceHandler2"...

The rest of the config used the MAC and IP of the 2nd OpenHab2 device and a second automation in the SmartThings app (selecting all of the devices I want to use)

But I may have missed something as OpenHab2 Discovery does not work.

**Comment by BobRak** [comment]
Just to make sure we are on the same page... Do you now have 2 RPi's pointing to the same smartthings hub? If so, I've done something similar. 

Here is what I've done:
In the smartthings IDE (https://graph.api.smartthings.com) I have:
- 1 device handler named: OpenHabDeviceHandler
- 1 SmartApp named: OpenHabAppV2
- 2 devices
device 1 points to the IP and mac of my RPi and uses OpenHabAppV2
device 2 points to the IP and mac of my PC (which is where my java development IDE and test environment runs) and uses OpenHapAppV2-Dev (OpenHabAppV2)

In the Smartthings App on my android phone I have the following SmartApps:
- OpenHabAppV2 - at the very bottom of the config screen it is set to notify the virtual device OpenHabDevice
- OpenHavAppV2-Dev - at the very bottom of the config screen it is set to notify virtual device OpenHavAppV2-Dev and the name is set to OpenHabAppV2-Dev

I think you can follow a similar configuration. In summary: 1 smart app, 1 device handler, 2 devices.

Bob

**Comment by 5witch** [comment]
What you suggested works.
