### ISSUE TITLE
Presence Sensor doesn't work

### ISSUE THREAD

**Issue by 5witch** [BobRak/OpenHAB-Smartthings#47]
I see that the Smartthings Presence Sensor isn't on the list of supported devices.  But I see    "presenceSensor": in the bobrak : OpenHabAppV2 SmartApp.  Should this work?

**Comment by BobRak** [comment]
Look at the Smartthing Installation document. Then look in the last section "Configuration in the Smartthings App" In the OpenHabAppV2 do you see the Presence Sensor and is it black and selectable? If so, can you select your arrival sensor? Or, is at already selected. Once it is selected in there I would expect it to be discoverable in the OpenHAB paperUI.

I now have my smartthings hub plugged in and I can try some things on it. I don't have my Raspberry Pi with me but I do have my PC and can do some testing in the development environment on my PC. I'll try to find some time next week to do that.

Bob

**Comment by 5witch** [comment]
I should have been more clear in my post.  I'm able to discover and add the Smartthings sensors to my OpenHAB2 configuration, but when I create dummy item in HABPanel, the status says NULL.

**Comment by BobRak** [comment]
Sorry for the delay in responding. I am still in the process of moving and don't have access to my Raspberry Pi. I do have my hub here and have gotten it setup and I have my PC with the OpenHAB development environment. Unfortunately I wasn't able to get habpanel running from within the runtime of my development IDE. However I can run the paperUI. I was able to create a presence sensor and access it using the basicUI. It works as expected. Please double check your config.

Here are the steps I used. Maybe you can replicate them and see if that helps with habpanel.

1. Add a presence sensor simulator in the smartthings app on my phone. You can just use your real presence sensor.
1. Restart openhab so discovery runs.
1. In the paperUI turn on simple item linking: configuration -> systems -> item linking = simple mode
1. From the paperUI inbox find the simulated presence sensor and click on it and in the dialog choose as "ADD AS THING"
1. Create a items file and define the presence sensor simulator. My definition looks like: String DiscoveredPresenceSimulator "Mike Maxwells Discovered presence simulator [%s]"                               { channel="smartthings:presenceSensor:Home:MikeMaxwellssimulator:presence"  }
1. create a sitemap and add the item. Mine looks like: Text item=DiscoveredPresenceSimulator
1. display the sitemap in the basicui
1. change the simulate presence sensor using the app on my phone and see the ui update.

Items 3-6 are described in the openhab documentation in the "New user tutorial" -> configuration of OpenHAB and creating a sitemap.

Please let me know if this helps.

**Comment by 5witch** [comment]
Thanks for the reply.  I just started going though your steps and noticed the Presence status in HABpanel is working now.  I hate when these things start working on their own.


-Joseph

________________________________

**Comment by BobRak** [comment]
OK, thanks for letting me know. I just got habpanel running in my development environment so I'm going to try it out as time permits.
