### ISSUE TITLE
Installation Steps for OpenHab

### ISSUE THREAD

**Issue by e8link** [BobRak/OpenHAB-Smartthings#49]
I'm at the 4th install step for OpenHab:

4. Add the appropriate configuration files (.things, .items, .sitemaps)

Which files are these in the archive?  Where do they go in openhab?

**Comment by BobRak** [comment]
This information is described in the OpenHAB documentation.  I started with OpenHAB before you could do most of the configuration with the PaperUI. See the documentation [here](https://www.openhab.org/docs/tutorial/sitemap.html). I think you will just need to create .items and .sitemaps.
