### ISSUE TITLE
How to get iPhone presence to openhab

### ISSUE THREAD

**Issue by 5witch** [BobRak/OpenHAB-Smartthings#51]
I selected my iPhone as one of the objects listed in the OpenHabAppV2 smart app, but I cannot discover it in Openhab.  This would be a great solution to the "presence problem".

**Comment by BobRak** [comment]
Sorry for the delay in response. The next two weeks are going to be very busy for me.

What kind of a device did it show up as in OpenHapAppV2? How was it discovered by the Smartthings hub. It isn't zigbee or ZWave.

**Comment by 5witch** [comment]
Under the "Presence Sensor" option in the OpenHABV2 app I see my iPhone and my wife's iPhone.  Presumably this is on account of installing the Smartthings app on these devices and using the geofencing features.

**Comment by BobRak** [comment]
Right now I am in the middle of moving and don't have my openHAB or Smartthings hub operating. When My move is complete I'll look into this. Probably near the end of Sept.

Did your presence sensor come from Marketplace -> Sensors -> Presence sensors -> Mobile Phone?

**Comment by 5witch** [comment]
Yes, and when I select "Connect Now from Marketplace -> Sensors -> Presence sensors -> Mobile Phone, I get a message saying "This mobile phone is already set up as a mobile presence device."

**Comment by BobRak** [comment]
I finally am back to working on the smartthings binding for openHab. I added the presence sensor to my Android phone. I have been able to discover it and add it to openHab.  

![image](https://user-images.githubusercontent.com/17749636/46695731-30a64900-cbc5-11e8-8944-77ba7be91e6b.png)

In the ST app on your phone are you seeing it and is it registering correctly? Have you added it to the OpenHabAppV2?

**Comment by 5witch** [comment]
I select the Phone in the list of presence sensors in the OpenHabAppV2.  But discovery does not find it.  I can add manually, but the .state is Null.

**Comment by BobRak** [comment]
I just deployed a new smartthings jar file to [my github repo](https://github.com/BobRak/OpenHAB-Smartthings/tree/master/org.openhab.binding.smartthings/target). You might start by downloading it. But, I don't think that I made any changes that should affect this problem. It is working correctly for me. Here is a picture of it in the PaperUI:
![image](https://user-images.githubusercontent.com/17749636/46908882-17abd980-cede-11e8-8efe-7ce52a585a5b.png)
Here is what the definition looks like:
![image](https://user-images.githubusercontent.com/17749636/46908897-50e44980-cede-11e8-8302-b9b6ff734d58.png)
Is yours defined as a String?

I'm not sure why it wasn't getting discovered. I did make one change to the discovery service that allows it to create things where the name is Smartthings is not valid in OpenHAB. These would be names that include special character other than letters, number, hyphen and underscore. I think it is important to figure out why it isn't being discovered. Please check the openHAB logs on you openHAB server.
