### ISSUE TITLE
Battery Level won't update

### ISSUE THREAD

**Issue by fals3illusion** [BobRak/OpenHAB-Smartthings#53]
Hello,

Been using the smarthings binging for a little while so far and works great besides one little problem.  Currently have two z wave dimmers that work flawlessly and one Schlage Century Touchscreen Deadbolt Door Lock.

TheDimmers and Lock portion works great. 
I'm having a problem with the battery polling.  I cannot get the battery to update.  

Here are my configurations:
THINGS
```
Bridge smartthings:smartthings:Home    [ smartthingsIp="192.168.1.119", smartthingsPort=39500 ] {
		Thing switchLevel             	BedroomLights          	[ smartthingsName="Bedroom Lights" ]
		
		Thing switchLevel              	KitchenLights           [ smartthingsName="Kitchen Lights" ]
		
		Thing lock						FrontDoorLock			[ smartthingsName="Front Door" ]
		Thing battery                  	FrontDoorBattery       	[ smartthingsName="Front Door" ]
		
}
```
ITEMS:
```
Dimmer  BedroomLights			"Bedroom Lights [%d %%]"			<slider>	(gZwave, gLights, gBedroom)	{ channel="smartthings:switchLevel:Home:BedroomLights:level" }
Dimmer  KitchenLights			"Kitchen Lights [%d %%]"			<slider>	(gZwave, gLights, gKitchen)	{ channel="smartthings:switchLevel:Home:KitchenLights:level" }
String	FrontDoorLock			"Front Door Lock [%s]"				<door>		(gZwave)					{ channel="smartthings:lock:Home:FrontDoor:lock" }  
Number  FrontDoorBattery    	"Front Door battery [%.0f]"  		<battery>   (gZwave)					{ channel="smartthings:battery:Home:FrontDoorBattery:battery" }  
```

Any help would be greatly appreciated!

Thanks!

**Comment by BobRak** [comment]
Your Things and Items definitions look good to me.  Have you included the battery in the OpenHabAppV2 SmartApp config? That is the only thing I can think of.
Bob

**Comment by BobRak** [comment]
Since I haven't heard back from you I assume you have resolved this. If you are still having problems please reopen the issue.

**Comment by fals3illusion** [comment]
Sorry, didn't see your response.  If you are talking about the battery in... [https://github.com/BobRak/OpenHAB-Smartthings/blob/master/org.openhab.binding.smartthings/target/smartthings/SmartApps/OpenHabAppV2.groovy]

I just copied the code, created, and published it as OpenHabAppV2
