### ISSUE TITLE
Bridge Configuration

### ISSUE THREAD

**Issue by naseemr** [BobRak/OpenHAB-Smartthings#6]
Hi BobRak,
I am new to OpenHAB, I am not clear about the section you have for Bridge Configuration. 
Where does the following goes Bridge smartthings:smartthings:Home    [ smartthingsIp="192.168.1.12", smartthingsPort=39500 ] { 

In discovery I cann add things but dont see anything when I click on select bridge.
Any help is much appreciated.
Thanks,

**Comment by BobRak** [comment]
Sorry for the slow reply. I configured openHAB using files and it seems like you are using PaperUI. The Bridge is part of the things configuration. Have you added Smartthings using the Add-ons panel? You can specify the ip and port of your hub in PaperUI using Configuration -> Things, then look for the "Smartthings Hub". Clicking on the "Smartthings Hub" item will let you edit it's configuration properties.
