### ISSUE TITLE
It is possibile

### ISSUE THREAD

**Issue by blademckain** [BobRak/OpenHAB-Smartthings#64]
It is possible with 
- this binding
- a samsung smartthings hub
- a samsung dishwasher
program that the dishwasher can start at an exact time?

**Comment by BobRak** [comment]
@blademckain Are you asking if it is possible to control a Samsung dishwasher with OpenHAB and this binding?  If that is the question, I am not sure. But you can figure it out this way: This binding requires the Smartthings **Classic** app on your phone. If you can control the dishwasher with the Classic app then you should be able to control it through OpenHAB with this binding.

**Comment by goopilot** [comment]
@BobRak 
I have the same question. Washer doesn't require a SmartThing hub, but I still see it in Smartthings Classic app, however when I'm following instruction at this step:

> 5. Scroll to the bottom and select My Apps
> 6. Select OpenHabAppV2
> -In the selection screen select the devices you want to interact with OpenHAB. Warning devices not enabled (lacking the check mark in the box for the specific device) will be ** ignored ** by OpenHAB.
> -Near the bottom of the screen is Notify this virtual device, click on it and select OpenHabDevice.
> -Finally click Done on the upper right.
> 

I don't see washer in the list of supported devices.

The bigger question here is absence of the Hub, is it possible to use myopenhab.org for communication between SmartThings cloud and OpenHab?

**Comment by BobRak** [comment]
If you don't see your washer (or the capabilities of it) in the OpenHabAppV2 then it must not be supported in the Smartthings "Classic" app. This binding only works with the Classic app. I started on this app 2 years ago and at that time the ST developers platform was centered around the ST Hub.  As best I can tell the hub isn't currently supported in the new developers platform [See this link.](https://smartthings.developer.samsung.com/develop/guides/hub/overview.html).  

I don't have any Smartthing appliances and therefore would not be able to do any testing even if I wanted to build a binding to the new ST developers platform using the ST cloud.

I don't know if the ST cloud can be integrated with the openHAB cloud service. My background is Java development and the myopenhab.org is a web/cloud based solution that is outside my expertise. You could post something on [openHAB Community website.](https://community.openhab.org)

**Comment by goopilot** [comment]
@BobRak thanks, I'll post it there and mention that you are already working on legacy Smarting platform.
