### ISSUE TITLE
install

### ISSUE THREAD

**Issue by Vikinge** [BobRak/OpenHAB-Smartthings#70]
I am currently testing both Home Assist and OpenHab as smart things replacement.   I started down the MQTT path but found HomeAssistant with smartthings (smartapp) worked great.  I put your .jar file into addons folder but (after reboot)  I do not see smartthings binding entry?  I completed all the smartthings steps (device handler and smartapp).  What am I missing to install your add-on to openhab (2.5.0-snapshot)?  I am running in docker and the /config folder structure is persistent.

**Comment by BobRak** [comment]
Hi @Vikinge 
I'm away from home and do not have access to my openHAB. But, here is what I think you need to do.

If you are configuring from files then just create your .things, .items and .sitemap files.

But, I am guessing you are configuring from PaperUI. With jar files put in the addons directory you do not need to go through the Addons -> binding -> ... steps. Files in addons are already installed. Just go to Inbox -> then click on "Search for Things". Hopefully Smartthings will show up there and you can select the Smartthings Hub. Add the IP of your ST hub and the port. Then you should be able search again and your devices will show up.

Also, have you followed the steps in the README.md for Discovery.

Let me know how it goes. I'll be back home later in the week.

**Comment by Vikinge** [comment]
thank you for the feedback.  I tried searching for things, but with no
smartthings binding listed, not sure how it could find anything.  I did
follow all the steps in the readme for setting up the smarthings side.  I
assume I cannot add the smarthings hub IP until i see an item or the
binding appears.  I may try using the latest 2.5.0 snapshot, I will let you
know if I make any progress.  Is there a log that would show if the
extension is being loaded?

**Comment by BobRak** [comment]
It talks about logs in the [troubleshooting document](https://github.com/BobRak/OpenHAB-Smartthings/blob/master/org.openhab.binding.smartthings/Troubleshooting.md). Also, the openHAB doc has a log section, [click here](https://www.openhab.org/docs/administration/logging.html).

See if there is anything about smartthings in the log.

Also, check that the smartthings...jar file has read and execute permissions.

**Comment by Vikinge** [comment]
I started over with raspberry PI instead of Docker.  Everything works
