### ISSUE TITLE
Binding not showing up in PaperUI

### ISSUE THREAD

**Issue by swapanshridhar** [BobRak/OpenHAB-Smartthings#74]
I referred to the README and following  [ISSUE LINK](https://github.com/BobRak/OpenHAB-Smartthings/issues/65).

As of now following has been done:
-----------------------------------

**On Smartthings Dev Hub**
1. Followed the [OpenHab Smart App installation on Smartthings Dev Hub ](https://github.com/BobRak/OpenHAB-Smartthings/blob/master/org.openhab.binding.smartthings/SmartthingsInstallation.md). This works fine and **Virtual Device** has been added.

**On OpenHab Server** 
1. Copied org.openhab.binding.smartthings-2.5.0-SNAPSHOT.jar to my /srv/openhab2-sys/addons/ location : 

```
$ ls -al /srv/openhab2-sys/addons/

-rw-rw-r--  1 openhabian openhabian 2107981 May 13 18:00 org.apache.common.codec.jar
-rwxrwxrwx  1 openhab    openhab      63507 May 12 16:37 org.openhab.binding.smartthings-2.5.0-SNAPSHOT.jar
-rw-rw-r--  1 openhab    openhab         70 May 28  2018 README
```

Also added a CODEC jar as i it was a suggestion somewhere that there may be a CODEC issue.

2. Restarted OpenHab Server

**But binding doesn't  show up on Paper UI and therefore I am not able to search the THING** on UI.**

So, requesting the following inputs:
-----------------------------------

- 1. In [Issue 65 reply](https://github.com/BobRak/OpenHAB-Smartthings/issues/65#issuecomment-471234926), following is mentioned : 

`4. Add the appropriate configuration files (.things, .items, .sitemaps)`
   Question : Shouldnt it be added automatically once my Binding is discovered and THING search goes fine. Please suggest.

- 2. Any inputs on overall setup that I have done and what else needs to be done to get the BINDING and SMARTTHING THING.

cc @BobRak  | @Garfield9988

**Comment by BobRak** [comment]
re:

> 4. Add the appropriate configuration files (.things, .items, .sitemaps)
> Question : Shouldnt it be added automatically once my Binding is discovered and THING search goes fine. Please suggest.
> 
You can either use the PaperUI to configure. This automatically uses something called Discovery to find all of your device. Or you can configure using files. You can read about this in the openHAB documentation. If you use discovery you with first have to add the Smartthings binding. This is covered in the [readme file](https://github.com/BobRak/OpenHAB-Smartthings/tree/master/org.openhab.binding.smartthings).

Are you sure you have completed the last step in the [smartthings installation](https://github.com/BobRak/OpenHAB-Smartthings/blob/master/org.openhab.binding.smartthings/SmartthingsInstallation.md). Without this step openHAB will not be able to find any of the devices.

Have you looked at the logs? You should see the Smartthings binding being loaded.  If it isn't being loaded then you will have to figure that out first. You can also use the karaf console to see if the binding is has been loaded by the OSGi framework. You can read about that in issue #69.

I'm leaving tomorrow and won't be home until early June. I'll have limited ability respond. Everything you have said so far makes me thing this is aa setup problem and not a problem with the binding. I would recommend you go through the installation instructions again and make  sure everything has been done and is correct.
