### ISSUE TITLE
No things are discovered via Smartthings binding

### ISSUE THREAD

**Issue by gezuka77** [BobRak/OpenHAB-Smartthings#75]
Hi,

I seem to have everything set up all right as I have the Smartthings side seemingly running with stuff added in the Smartthings Classic. I even have the Configuration > Things >Smartthings Hub reporting green (IP and port added). But when i go to Inbox > Smartthings Binding > Search nothing is showing up... RPI is restarted already.

This is what i see in the log:

> 2019-05-15 16:42:19.270 [INFO ] [hings.internal.SmartthingsHttpClient] - Sent message "{"discovery": "yes", "openHabStartTime": 1557927739036}" with path "/discovery" to the Smartthings hub, recieved HTTP status 202

**Comment by BobRak** [comment]
@gezuka77 
**First**
Have you completed the last step of the [ST installation (Configuration in the Smartthings Classic App)](https://github.com/BobRak/OpenHAB-Smartthings/blob/master/org.openhab.binding.smartthings/SmartthingsInstallation.md)? Without that nothing will be discovered.

**Second**
Following log entry you send me you should see the hub send back data about  the devices discovered.If nothing is being is being sent back either the above item hasn't been completed. Or, you haven't configured your device correctly. Especially make sure you are entering the correct mac address of your openHAB server. That is in the "Create the device" step of the above instructions.

**Third**
See the troubleshooting document and look at the "Viewing the smartthings logs" If you are seeing data being sent from smartthings but not being received in openHAB the "Create the device" step.

**Fourth**
This looks like an installation/setup issue. Go through all of the installation instructions again and make sure you have done everything correctly and have covered all of the steps. It is a long and complicated process and is easy to miss a step.

I am leaving tomorrow and will be gone until early June. I'll have limited internet access while I am away.

**Comment by gezuka77** [comment]
@BobRak
I have double checked everything and replaced the MAC address written with capitals to small caps. But I don't think that should matter, right?
Anyhow, is has suddenly started to discover my ST devices!

Thanks

**Comment by BobRak** [comment]
@gezuka77 

Glad it is working now.

If doesn't matter if the mac is upper or lower case.

Bob

**Comment by Redapted** [comment]
For future readers; this happened for mine as well. Turns out I had accidentally enabled both the wifi and connected via ethernet. Disconnected the wifi, and it worked fine.

**Comment by BobRak** [comment]
@Redapted 
Thanks for the feedback. At some point I hope to write an FAQ and will include this. One quick question - The WiFi was enabled on the ST hub? Just want to make sure I have the right device. If it is the hub then you must have a v3 hub. Mine is V2 and hardwired only.
Thanks,
Bob

**Comment by Redapted** [comment]
@BobRak Ah, no sorry. Hub is hard-wired. The wifi was enabled on the OpenHab device (Raspberry Pi).
