### ISSUE TITLE
Can I use Smartthings instead of RaspBee/CC2531 ?

### ISSUE THREAD

**Issue by 4val0v** [BobRak/OpenHAB-Smartthings#77]
1. Hi, can Smartthings be used instead of ConBee / CC2531 to communicate with other ZigBee/Z-Wave devices?
2. Can I configure the behavior of devices in OpenHab without using the Samsung cloud?
3. Can Smartthings be transferred to a fully local mode and use OpenHab as a server?
4. Can I add absolutely any ZigBee devices whose support is not stated in Smartthings, but is present in OpenHab [(Add-ons)](https://www.openhab.org/addons/) ?
5. Which version of Smartthings is worth buying v2 _(2015)_ or v3 _(2018)_?

**Comment by BobRak** [comment]
Hi 4valv0

Here are my comments on your questions. Most of these are more related to smartthings and would be best posted on the [smartthings community forum](https://community.smartthings.com/).

1. The Smartthings hub does communicate with ZigBee/Z-Wave devices? I don't know anything about  ConBee / CC2531.

2. No, again you can find more information of this topic in the Smartthings community.

**Comment by BobRak** [comment]
3.No. openHAB does not do the same things as the ST cloud.

4.I'm not sure what you are asking here. This binding only talks to ST. There are other openHAB bindings that work with other Z-wave and Zigbee hardware. I have never used them.

5. I have a v2 hub. This is really a question for the ST community.

Bob
