### ISSUE TITLE
Cannot communicate from Windows 10 OpenHab 2.4 to SmartThings

### ISSUE THREAD

**Issue by ajbastien** [BobRak/OpenHAB-Smartthings#79]
I am getting Address in use errors (I get this for other bindings but they still seem to work so might not be important.  From SmartThings dev app I get errors too trying to send to openHab Hub.  See attached logs. 

Any help appreciated.  Thanks

[smartthingsDevTools.log](https://github.com/BobRak/OpenHAB-Smartthings/files/3322856/smartthingsDevTools.log)
[smartthingsOpenHab.log](https://github.com/BobRak/OpenHAB-Smartthings/files/3322857/smartthingsOpenHab.log)
[smartthings.items.txt](https://github.com/BobRak/OpenHAB-Smartthings/files/3322862/smartthings.items.txt)
[smartthings.things.txt](https://github.com/BobRak/OpenHAB-Smartthings/files/3322863/smartthings.things.txt)

**Comment by BobRak** [comment]
Sorry for the delayed response, I've been out of town for a few days.

Here are some things to check.

1. Make sure you don't have 2 smartthings binding jar files (with different version numbers) in your addons folder.

2. Make sure there are not 2 copies of the smartthings binding loaded in the OSGI framework. You will need to use the osgi console for this. instructions are [here](https://www.openhab.org/docs/administration/console.html).

3. Verify that the parameters in your Smartthings device are correct. Especially the mac address. Instructions are [here](https://github.com/BobRak/OpenHAB-Smartthings/blob/master/org.openhab.binding.smartthings/SmartthingsInstallation.md#create-the-device). The mac address here has to be the mac address of the OpenHAB server. Looking at the errors in SmartthingsDevTools.log it seems unhappy with the mac address.

4. If none of these help then restart the machine OpenHAB is running on. And while you are at it, restart your Smartthings hub.

5. Lastly, walk through the install instructions again and make sure everything is correct. It is a long and complicated setup.

Please let me know what you find. Eventually I want to write an FAQ document nd capture problems people run into.

Bob
