### ISSUE TITLE
2 Way communication

### ISSUE THREAD

**Issue by adampv** [BobRak/OpenHAB-Smartthings#8]
@BobRak 
Thank you very much for this binding - its working fantastically.

However, it says that there is two-way communication? so far I have only been able to get Smartthings devices to show in OpenHab. It would also be useful for me to put some OpenHab devices in Smartthings.. is this possible?

**Comment by BobRak** [comment]
By two-way communications I meant that You can change the state of a device from OpenHAB. And, if you change a device manually of from another app the state of that device in OpenHAB will be updated. For instance you can turn a switch on from OpenHAB. And, if you turn it on manually or from the Smartthings app then OpenHAB will be updated with the current state.

It might be possible to build an interface that made anything in OpenHAB available to Smartthings. I would have to think about that but it is not something I can take on right now.

Bob
