### ISSUE TITLE
Just received this email ...

### ISSUE THREAD

**Issue by edwolfe807** [BobRak/OpenHAB-Smartthings#83]
I just received the email below.  It looks like they are forcing a switch to the new app!?  Is that going to effectively break openhab's ability to use Smartthings?

> Get ready to make the switch
> --
> Many of the features from SmartThings   Classic are now included in the new SmartThings app!      We have started asking some users to transition to the new app. However, a   few of the features you know and love are not quite available yet. Feel free   to start exploring the new app and we will notify you again soon when all of   your settings are ready to migrate.      If you have not transitioned to a Samsung account yet, follow the steps in   the banner in the SmartThings Classic app to get started.
>  
>  
>  
> If you need help with this transition, check   out our FAQ or our   customer service team would be happy to answer any questions. Get in touch   with us at support@smartthings.com.         Thank you,   The SmartThings team

**Comment by BobRak** [comment]
I installed the new app on my phone today and everything is fine. I don't remember why I said this binding needs the Smartthings Classic app. Maybe there was something missing earlier. When you install the new app on your phone please let me know if everything is OK or if you have problems. Thanks,
