### ISSUE TITLE
OpenHabDeviceHandler.groovy is not compiling in  Smartthings developers tools.

### ISSUE THREAD

**Issue by basem99h** [BobRak/OpenHAB-Smartthings#85]
hello 
I created the  **OpenHabAppV**2 application successfully from the attached code, but when i copied the code for the *OpenHabDeviceHandler.groovy*, it shows the following error 
![image](https://user-images.githubusercontent.com/60322155/73138472-e8d65a00-4073-11ea-8717-61e5fedd96c0.png)

any advice 
Thank you

**Comment by BobRak** [comment]
The OpenHabDeviceHandler is created in the My Device Handlers tab (not in the SmartApps tab)

**Comment by basem99h** [comment]
Thank you for your help
I am very new on this, this is silly mistake 
Will test and post the results 🤗

**Comment by basem99h** [comment]
@BobRak 
thank you, devicehandler is published and is ok now
can you help me how to get the mac adress of the opennhab server in order to create device Using the Smartthings developers tools
i am using windows pc a server for the openab, and when i get the pysical devices mac address (using the cmd : ipconfig /all)i had many devices : 
![image](https://user-images.githubusercontent.com/60322155/74250055-22a59280-4cfb-11ea-9075-84c0a8b7d426.png)

thank you again

**Comment by BobRak** [comment]
You want to use the one that says "Killer Wireless". This is the mac
address of the actual wireless adapter.

Bob
