### ISSUE TITLE
Binding is empty

### ISSUE THREAD

**Issue by petervargait** [BobRak/OpenHAB-Smartthings#87]
Hi I have followed the installation of the bindings. I have the app on SmartThings  up and running. Binding shows up in Paper UI however there is no option to add Things as I am selecting add things, choose Smartthings  binding  I got a completely empty completely empty.

**Comment by BobRak** [comment]
Have you followed the Samrtthings installation instructions located [here](https://github.com/BobRak/OpenHAB-Smartthings/blob/master/org.openhab.binding.smartthings/SmartthingsInstallation.md)? Also, make sure to complete the last step: **Configuration in the Smartthings Classic App**

Do the openHAB logs show any things being discovered? You should see messages similar to: `INFO  o.o.b.s.i.d.SmartthingsDiscoveryService:208 - Discovery: Creating device: ThingType switch with name Living Room Light`

Please go back and verify that you have not missed any steps in the installation instructions.

**Comment by petervargait** [comment]
Thank a lot for the quick response, yes pls see the pic. My ACa also appear in the app. Nothing shows in the logs . I can see Smartthings binding in PaperUI but when I’d like to add a thing from binding than I got an empty screen , nothing shows up in the logs

**Comment by BobRak** [comment]
Is this still an issue? In your previous comment you mentioned a pic which I'm not finding. I'm going to close the issue but please feel free to reopen if you have additional questions.

**Comment by petervargait** [comment]
Thanks it can be closed but I did report second one that not of my devices
are discovered
